### ISSUE TITLE
Does it work with rosetta drone ?

### ISSUE THREAD

**Issue by robbiedood** [CopterExpress/mavlink-websocket#1]
Dear mavlink-websocket owner and users,

The package is very useful, which enabling browser-to-mavlink communication via websocket.
But we were wondering if it could work with [rosetta drone](https://github.com/The1only/rosettadrone), which is a mavlink wrapper, translating DJI drone language to mavlink, and send mavlink data stream out.  And we are looking for direct way to translate mavlink to websocket for browser.

Hope to hear your expertise. 

Best,
-- Luke

**Comment by okalachev** [comment]
`mavlink-websocket.py` just proxies the mavlink messages to websockets and vice versa, so it should generally work with any mavlink device.

But it has [lists](https://github.com/CopterExpress/mavlink-websocket/blob/master/mavlink-websocket/mavlink-websocket.py#L27) for allowed outcoming and incoming messages (and minimum interval limits). These lists should be updated for specific application and mavlink device.
